### ISSUE TITLE
Error Retrieving Private Key for Shielded Address

### ISSUE THREAD

**Issue by BleezInTheTrap** [BTCPrivate/bitcoin-private-full-node-wallet#11]
Successful creation of New Z-address, but unable to obtain the private key through the right-click or Wallet toolbar menus

![screenshot 2018-03-11 20 37 24](https://user-images.githubusercontent.com/33327087/37261644-299c4dd0-256c-11e8-980a-df72474f2a14.png)

debug log:

[AWT-EventQueue-0] [Sun Mar 11 20:34:10 CDT 2018] [ERROR] Unexpected error:  
com.vaklinov.zcashui.ZCashClientCaller$WalletCallException: Error response from wallet: error code: -3
error message:
Address does not refer to a key

	at com.vaklinov.zcashui.ZCashClientCaller.executeCommandAndGetSingleStringResponse(ZCashClientCaller.java:1118)
	at com.vaklinov.zcashui.ZCashClientCaller.executeCommandAndGetSingleStringResponse(ZCashClientCaller.java:1089)
	at com.vaklinov.zcashui.ZCashClientCaller.executeCommandAndGetSingleStringResponse(ZCashClientCaller.java:1082)
	at com.vaklinov.zcashui.ZCashClientCaller.getTPrivateKey(ZCashClientCaller.java:916)
	at com.vaklinov.zcashui.WalletOperations.showPrivateKey(WalletOperations.java:368)
	at com.vaklinov.zcashui.ZCashUI$3.actionPerformed(ZCashUI.java:349)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by BleezInTheTrap** [comment]
I upgraded to release 1.0.2

All addresses and keys remained intact, and the error has resolved.
