### ISSUE TITLE
Wallet Won't Open - Mac

### ISSUE THREAD

**Issue by Fritzerton** [BTCPrivate/bitcoin-private-full-node-wallet#11]
After unzipping I get the message "The application BitcoinPrivateDesktopWallet Can't be Opened
<img width="455" alt="screen shot 2018-03-03 at 12 49 58 pm" src="https://user-images.githubusercontent.com/35083649/36937491-1e038cd0-1ee2-11e8-8102-46868abe85d8.png">

**Comment by sciack76** [comment]
same here

**Comment by Fritzerton** [comment]
Running latest Mac OS and Java. I've used previous beta swing and electrum ZCL wallets but all files from those have been removed.

**Comment by RightTwiceADay** [comment]
Same here. OS 10.12.5

**Comment by alex-lucid** [comment]
Extract all files from the .app and launch from the terminal:
sudo java -jar BitcoinPrivateDesktopWallet.jar

**Comment by pogoetic** [comment]
This solves the initial problem but others present themselves after the 900MB keyfile is downloaded:

[main] [Sat Mar 03 13:31:43 EST 2018] [INFO] Splash: btcpd already running... 
[main] [Sat Mar 03 13:31:52 EST 2018] [ERROR] Unexpected error:  
java.io.IOException: Cannot run program "/Users/evgenypogorelov/Desktop/BitcoinPrivateDesktopWallet/btcp-cli": error=13, Permission denied
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:485)
	at com.vaklinov.zcashui.CommandExecutor.execute(CommandExecutor.java:68)
	at com.vaklinov.zcashui.ZCashClientCaller.getDaemonRawRuntimeInfo(ZCashClientCaller.java:168)
	at com.vaklinov.zcashui.StartupProgressDialog.waitForStartup(StartupProgressDialog.java:131)
	at com.vaklinov.zcashui.ZCashUI.main(ZCashUI.java:633)
Caused by: java.io.IOException: error=13, Permission denied
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 6 more

**Comment by alex-lucid** [comment]
sudo chmod u+x btcpd
sudo chmod u+x btcp-cli

**Comment by RightTwiceADay** [comment]
i just checked the download page again and the previous file has been replaced. The new zip file works for me!

**Comment by pogoetic** [comment]
Thanks alex-lucid! Next error, seems like a missing configuration file which i'm not seeing in any of the subdirectories: 
```
[main] [Sat Mar 03 13:38:59 EST 2018] [INFO] unexpected daemon info: Error reading configuration file: Missing btcprivate.conf
 
[main] [Sat Mar 03 13:38:59 EST 2018] [ERROR] Unexpected error:  
java.io.IOException: com.eclipsesource.json.ParseException: Expected value at 1:1
	at com.vaklinov.zcashui.ZCashClientCaller.getDaemonRawRuntimeInfo(ZCashClientCaller.java:199)
	at com.vaklinov.zcashui.StartupProgressDialog.waitForStartup(StartupProgressDialog.java:131)
	at com.vaklinov.zcashui.ZCashUI.main(ZCashUI.java:633)
Caused by: com.eclipsesource.json.ParseException: Expected value at 1:1
	at com.eclipsesource.json.JsonParser.error(JsonParser.java:490)
	at com.eclipsesource.json.JsonParser.expected(JsonParser.java:486)
	at com.eclipsesource.json.JsonParser.readValue(JsonParser.java:193)
	at com.eclipsesource.json.JsonParser.parse(JsonParser.java:152)
	at com.eclipsesource.json.JsonParser.parse(JsonParser.java:91)
	at com.eclipsesource.json.Json.parse(Json.java:295)
	at com.vaklinov.zcashui.ZCashClientCaller.getDaemonRawRuntimeInfo(ZCashClientCaller.java:195)
	... 2 more
```

**Comment by alex-lucid** [comment]
Basically, just do chmod for all executables in .app bundle and it will work

**Comment by Fritzerton** [comment]
The new file file on the github is working
