### ISSUE TITLE
Obtaining secret from z-Adress not work

### ISSUE THREAD

**Issue by atox42** [BTCPrivate/bitcoin-private-full-node-wallet#31]
I get a error if i want to receive the secret-Key from a z-Adress :) 

Best regards and thx for the GREAT WORK!!

Alex

![bildschirmfoto 2018-03-04 um 20 30 26](https://user-images.githubusercontent.com/37041341/36949605-eaae0630-1fea-11e8-95ee-9d58d7c1149e.png)

**Comment by Pega88** [comment]
Hi @atox42 , which version of OS X are you running? And which version of the wallet? 1.0.0 or the updated 1.0.1?

**Comment by atox42** [comment]
Hi Niels it is the 1.0.1

OS X Version 10.13.3

THX :)

**Comment by Killoren** [comment]
Trying to export a private key from a newly generated Z address. Running wallet version 1.0.1 on windows 10 pro 64 bit. 

I am receiving the follow error 
"Error in obtaining private key: Error response from wallet: error code: -3 error message: Address does not refer to a key." 

This is occurring on 4 newly generated Z address in the Desktop GUI wallet 1.0.1. 1 created by the message tab, 2 created by a sweeping ZCL and BTC keys and 1 created by me. Blockchain is 100% synced. I am able to export T address just fine. 

Any ideas as to what is occurring or how to get the Z address private keys?

Thanks

**Comment by Pega88** [comment]
investigating, will report shortly.

any useful logs in 
%AppData%/Roaming/btcprivate/debug.log (windows)
~/Library/Application\ Support/BTCPrivate/debug.log (mac)

?

**Comment by Killoren** [comment]
I checked the %AppData%/Roaming/btcprivate/debug.log (windows) and did not see anything related. At least that I can discern. 

I am running Java build 1.8.0_161-b12

I did see the following right after attempting to export a private key from a Z address in the %AppData%/Local/BTCPrivateDesktopWallet/BitcoinPrivateGUIWallet_2018_3_debug.log

[AWT-EventQueue-0] [Sun Mar 04 15:37:41 CST 2018] [ERROR] Unexpected error:  
com.vaklinov.zcashui.ZCashClientCaller$WalletCallException: Error response from wallet: error code: -3
error message:
Address does not refer to a key

	at com.vaklinov.zcashui.ZCashClientCaller.executeCommandAndGetSingleStringResponse(ZCashClientCaller.java:1118)
	at com.vaklinov.zcashui.ZCashClientCaller.executeCommandAndGetSingleStringResponse(ZCashClientCaller.java:1089)
	at com.vaklinov.zcashui.ZCashClientCaller.executeCommandAndGetSingleStringResponse(ZCashClientCaller.java:1082)
	at com.vaklinov.zcashui.ZCashClientCaller.getTPrivateKey(ZCashClientCaller.java:916)
	at com.vaklinov.zcashui.AddressTable$1.actionPerformed(AddressTable.java:90)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by Pega88** [comment]
fixed it https://github.com/BTCPrivate/bitcoin-private-full-node-wallet/commit/c2e57f0010dbb82fb831c316e95f3c06c8f05da8, was still checking prefix on testnet syntax (zz) rather than mainnet (zk).
will be released with 1.0.2. 
@ch4ot1c
