### ISSUE TITLE
Mac wallet wont start, requires chmod +x btcpd and btcp-cli

### ISSUE THREAD

**Issue by lukevenediger** [BTCPrivate/bitcoin-private-full-node-wallet#6]
Hi,

After unpacking the mac release and trying to open the app it seems to error out immediately with "The application “BitcoinPrivateDesktopWallet” can’t be opened."

I'm running 10.12.6 with JRE 1.8.0_73

**Comment by lukevenediger** [comment]
Here's what I did to get it working on Mac:

1. Download the mac release
2. Open Terminal and go to the /Applications/BitcoinPrivateDesktopWallet.app/ directory
`cd /Applications/BitcoinPrivateDesktopWallet.app/`
3. Make btcp-cli and btcpd executable:
`chmod +x btcpd; chmod +x btcpd`
4. Run the app:
`java -jar Java/BitcoinPrivateDesktopWallet.jar`

**Comment by SpencerBoyd** [comment]
Thanks for helping Luke! I am still gettin an error when trying to make the apps executable, "chmod: btcpd: No such file or directory ; chmod: btcpd: No such file or directory"

Any ideas?

**Comment by RightTwiceADay** [comment]
Same here. The app wont start on my mac and when typing chmod "+x btcpd; chmod +x btcpd" I get the same error ("chmod: btcpd: No such file or directory ; chmod: btcpd: No such file or directory").

**Comment by lukevenediger** [comment]
Hey guys, sorry, I missed a step, give me a few mins to update the instructions

**Comment by lukevenediger** [comment]
Please review step 2 and try again? You need to go to `/Applications/BitcoinPrivateDesktopWallet.app/Contents`

**Comment by SpencerBoyd** [comment]
Awesome, thank you so much. That did the trick!

**Comment by RightTwiceADay** [comment]
That's great thanks! But what's supposed to happen then? Should the app run? Sorry for being a total noob but I get this message: "Exception in thread "main" java.lang.UnsupportedClassVersionError: com/vaklinov/zcashui/ZCashUI : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)"

**Comment by SpencerBoyd** [comment]
I got a permission denied error.

[main] [Sat Mar 03 09:53:58 PST 2018] [INFO] Splash: btcpd already running... 
[main] [Sat Mar 03 09:54:07 PST 2018] [ERROR] Unexpected error:  
java.io.IOException: Cannot run program "/Applications/BitcoinPrivateDesktopWallet.app/Contents/btcp-cli": error=13, Permission denied

**Comment by nqduy1984** [comment]
1. cd /Applications/BitcoinPrivateDesktopWallet.app/Contents
2. chmod +x btcpd
3. chmod +x btcp-cli
4. java -jar Java/BitcoinPrivateDesktopWallet.jar

Make sure your Mac have installed java jdk

**Comment by KimboKastekniv** [comment]
Done everything, the wallet opened, download the files and then I got that error:

Window wallet error message:
Unexpected Exception
An unexpected error (Exception) has occurred.
com.eclipsesource.json.ParseException: Expected value at 1:1
See the console/logfile output for more detailed error information!

Console error:
[main] [Sat Mar 03 20:10:15 EET 2018] [ERROR] Unexpected error:  
java.io.IOException: com.eclipsesource.json.ParseException: Expected value at 1:1
	at com.vaklinov.zcashui.ZCashClientCaller.getDaemonRawRuntimeInfo(ZCashClientCaller.java:199)
	at com.vaklinov.zcashui.StartupProgressDialog.waitForStartup(StartupProgressDialog.java:131)
	at com.vaklinov.zcashui.ZCashUI.main(ZCashUI.java:633)
Caused by: com.eclipsesource.json.ParseException: Expected value at 1:1
	at com.eclipsesource.json.JsonParser.error(JsonParser.java:490)
	at com.eclipsesource.json.JsonParser.expected(JsonParser.java:486)
	at com.eclipsesource.json.JsonParser.readValue(JsonParser.java:193)
	at com.eclipsesource.json.JsonParser.parse(JsonParser.java:152)
	at com.eclipsesource.json.JsonParser.parse(JsonParser.java:91)
	at com.eclipsesource.json.Json.parse(Json.java:295)
	at com.vaklinov.zcashui.ZCashClientCaller.getDaemonRawRuntimeInfo(ZCashClientCaller.java:195)
	... 2 more

**Comment by RightTwiceADay** [comment]
Thank you nqduy1984, that's what I did already but it didn't work for me unfortulately.

**Comment by SpencerBoyd** [comment]
Cool, I was missing step 3. I got it working now I think, but claiming coins with this wallet seems risky at best?

**Comment by iamhydrogen** [comment]
I also get the permission denied error...

**Comment by RightTwiceADay** [comment]
i just checked the download page again and the previous file has been replaced. The new zip file works for me!

**Comment by SpencerBoyd** [comment]
Good call, RTAD. New Zip is working great!

**Comment by KimboKastekniv** [comment]
Still getting the same error with the new replaced zip file:

Unexpected Exception
An unexpected error (Exception) has occurred.
com.eclipsesource.json.ParseException: Expected value at 1:1
See the console/logfile output for more detailed error information!

**Comment by ch4ot1c** [comment]
Sorry about that - indeed `sudo chmod +x btcpd; sudo chmod +x btcp-cli`
