### ISSUE TITLE
Error: couldn't connect to server: EOF reached (code 1)

### ISSUE THREAD

**Issue by irishismyname** [BTCPrivate/bitcoin-private-full-node-wallet#7]
I've had the full node wallet running for a few days now, and starting this morning I've been getting this:

![image](https://user-images.githubusercontent.com/34629432/37254816-9b67183a-2519-11e8-959e-69b0a0b114df.png)

`[Thread-83] [Sun Mar 11 10:42:27 EDT 2018] [ERROR] Unexpected error:  
org.btcprivate.wallets.fullnode.daemon.BTCPClientCaller$WalletCallException: Error response from wallet: error: couldn't connect to server: EOF reached (code 1)
(make sure server is running and you are connecting to the correct RPC port)`

	at org.btcprivate.wallets.fullnode.daemon.BTCPClientCaller.executeCommandAndGetSingleStringResponse(BTCPClientCaller.java:943)
	at org.btcprivate.wallets.fullnode.daemon.BTCPClientCaller.executeCommandAndGetSingleStringResponse(BTCPClientCaller.java:920)
	at org.btcprivate.wallets.fullnode.daemon.BTCPClientCaller.executeCommandAndGetJsonValue(BTCPClientCaller.java:893)
	at org.btcprivate.wallets.fullnode.daemon.BTCPClientCaller.executeCommandAndGetJsonArray(BTCPClientCaller.java:875)
	at org.btcprivate.wallets.fullnode.daemon.BTCPClientCaller.executeCommandAndGetJsonArray(BTCPClientCaller.java:869)
	at org.btcprivate.wallets.fullnode.daemon.BTCPClientCaller.getWalletZAddresses(BTCPClientCaller.java:194)
	at org.btcprivate.wallets.fullnode.ui.AddressesPanel.getAddressBalanceDataFromWallet(AddressesPanel.java:331)
	at org.btcprivate.wallets.fullnode.ui.AddressesPanel.access$000(AddressesPanel.java:43)
	at org.btcprivate.wallets.fullnode.ui.AddressesPanel$1.gatherData(AddressesPanel.java:120)
	at org.btcprivate.wallets.fullnode.ui.AddressesPanel$1.gatherData(AddressesPanel.java:115)
	at org.btcprivate.wallets.fullnode.daemon.DataGatheringThread.doOneGathering(DataGatheringThread.java:167)
	at org.btcprivate.wallets.fullnode.daemon.DataGatheringThread.run(DataGatheringThread.java:148)

I don't think btcpd was running, but I can't be sure because I was too quick to restart the wallet. Is there a separate log for btcpd?

**Comment by greenman57** [comment]
I'm also having this issue.
![capture](https://user-images.githubusercontent.com/35261504/37256197-bb76e3a8-252d-11e8-8004-dc218e4065c8.JPG)

**Comment by irishismyname** [comment]
Confirmed that btcpd is not running when this message is generated. Also noticed btcp-cli.exe starting and stopping over and over. Still haven't found any logs for btcpd, but I'm running it via powershell now so I can at least catch the termination message.

**Comment by fokep** [comment]
See the [BitcoinPrivate Desktop GUI Wallet troubleshooting guide](https://github.com/BTCPrivate/bitcoin-private-full-node-wallet/blob/master/docs/TroubleshootingGuide.md) for this specific error.

Edit: BTW there is not (by default) a "separate"/complete debug running for btcpd but it can be enabled by running (it will still print everything to debug.log in the Roaming folder)

`btcpd -debug=1`

See attached file for reference (output of `btcpd --help -help-debug`)
[btcpd--help-help-debug.txt](https://github.com/BTCPrivate/bitcoin-private-full-node-wallet/files/1803318/btcpd--help-help-debug.txt)

Edit 2: If this error is caused by block-chain corruption due to abruptly stopping the btcpd when closing the wallet (I believe this was a known issue with the windows ZCL wallet and I don't know if it has been addressed properly for BTCP) it may be prevented by using the btcp-cli to stop btcpd before you close it. Out of habit I always start the deamon before opening the wallet GUI, running `btcpd` and also to stop it with `btcp-cli stop` before closing the GUI.

You can make two simple .bat files to make this easier (start.bat and stop.bat):

```
echo "Starting the Bitcoin Private Wallet"
btcpd.exe
@pause
```

and 

```
echo "Stopping the Bitcoin Private Wallet"
btcp-cli.exe stop
@pause
```

**Comment by ch4ot1c** [comment]
The RPC timeouts have been adjusted, in the posted release.

**Comment by irishismyname** [comment]
After running btcpd from powershell, saw that the termination message was "out of disk space" :B whoops! Could it be possible to pass that error over to the GUI?

**Comment by ch4ot1c** [comment]
Thank you for the followup - can you post that exact error message? The EOF one can be enough to err in the GUI, but the Disk Space one would be nice.

**Comment by felipelalli** [comment]
I don't know if it's directly related to the issue, but I had a problem with `Error: couldn't connect to server: EOF reached` in Bitcoin Core, and I solved it by simply disabling HTTP Keep Alive on my HTTP client:

```go
	we.rpcClient = jsonrpc.NewClientWithOpts(we.url, &jsonrpc.RPCClientOpts{
		CustomHeaders: map[string]string{
			"Authorization": "Basic " +
				base64.StdEncoding.EncodeToString([]byte(we.user+":"+we.password)),
		},
		HTTPClient: &http.Client{
			Timeout: timeoutSecs * time.Second,
			Transport: &http.Transport{
				DisableKeepAlives: true,
			},
		},
	})
```
